#
# Default configuration options for LEAP Certificate Authority Daemon
#

#
# Certificate Authority
#
ca_key_path: "./test/files/ca.key"
ca_key_password: nil
ca_cert_path: "./test/files/ca.crt"

#
# Certificate pool
#
max_pool_size: 100
client_cert_lifespan: 2
client_cert_bit_size: 2024
client_cert_hash: "SHA256"

#
# Database
#
db_name: "client_certificates"
couch_connection:
  protocol: "http"
  host: "localhost"
  port: 5984
  username: ~
  password: ~
  prefix: ""
  suffix: ""
  join: "_"